<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

/**
 * WhatsApp Cloud API integration.
 *
 * One settings row per vendor: vendor 1 is the Order Click platform number (answers questions
 * about registration, plans and the service), and any merchant can later connect their own
 * number to answer questions about their own business.
 *
 * The webhook identifies the business by the `phone_number_id` Meta sends, which is what keeps
 * one merchant's data from ever reaching another merchant's customer.
 */
return new class extends Migration
{
    public function up(): void
    {
        if (!Schema::hasTable('whatsapp_settings')) {
            Schema::create('whatsapp_settings', function (Blueprint $t) {
                $t->id();
                $t->unsignedBigInteger('vendor_id')->unique();      // 1 = the Order Click platform number
                $t->string('display_number')->nullable();           // +973 3307 0341
                $t->string('phone_number_id')->nullable()->index(); // Meta Phone Number ID
                $t->string('waba_id')->nullable();                  // WhatsApp Business Account ID
                $t->text('access_token')->nullable();               // permanent system-user token (encrypted)
                $t->string('app_secret')->nullable();               // for X-Hub-Signature-256 verification
                $t->string('verify_token')->nullable();             // webhook handshake, generated by us
                $t->string('api_version', 10)->default('v21.0');
                $t->tinyInteger('is_active')->default(2);           // 1 live, 2 off
                $t->tinyInteger('ai_enabled')->default(1);          // AI auto-replies on/off
                $t->text('ai_greeting')->nullable();
                $t->text('ai_instructions')->nullable();            // extra tone/scope guidance
                $t->timestamps();
            });
        }

        // One row per customer conversation, per business.
        if (!Schema::hasTable('whatsapp_conversations')) {
            Schema::create('whatsapp_conversations', function (Blueprint $t) {
                $t->id();
                $t->unsignedBigInteger('vendor_id')->index();
                $t->string('wa_id')->index();                       // the customer's WhatsApp number
                $t->string('profile_name')->nullable();
                // bot = AI answers automatically · human = an admin has taken over
                $t->string('handled_by', 10)->default('bot');
                $t->unsignedBigInteger('assigned_to')->nullable();
                $t->timestamp('last_message_at')->nullable();
                $t->unsignedInteger('unread')->default(0);
                $t->timestamps();
                $t->unique(['vendor_id', 'wa_id']);
            });
        }

        if (!Schema::hasTable('whatsapp_chat_messages')) {
            Schema::create('whatsapp_chat_messages', function (Blueprint $t) {
                $t->id();
                $t->unsignedBigInteger('conversation_id')->index();
                $t->unsignedBigInteger('vendor_id')->index();
                $t->string('direction', 10);                        // in | out
                $t->string('wa_message_id')->nullable()->index();   // Meta id, also used to de-duplicate
                $t->string('type', 20)->default('text');
                $t->text('body')->nullable();
                $t->string('sent_by', 10)->nullable();              // ai | admin | system
                $t->string('status', 20)->nullable();               // sent | delivered | read | failed
                $t->text('error')->nullable();
                $t->timestamps();
            });
        }

        // The merchant's own Q&A knowledge base. `product_id` stays for the existing per-product
        // Q&A; a NULL product_id means a business-wide entry the AI may use on any channel.
        Schema::table('question_answer', function (Blueprint $t) {
            if (!Schema::hasColumn('question_answer', 'is_available')) $t->tinyInteger('is_available')->default(1)->after('answer');
            if (!Schema::hasColumn('question_answer', 'reorder_id'))   $t->unsignedInteger('reorder_id')->default(0)->after('is_available');
            // knowledge_base = merchant-authored FAQ · product = a customer question on a product
            if (!Schema::hasColumn('question_answer', 'source'))       $t->string('source', 20)->default('product')->after('reorder_id');
        });
        DB::table('question_answer')->whereNull('product_id')->update(['source' => 'knowledge_base']);

        // Seed the platform row so the admin page has something to edit, with a verify token
        // already generated — the client needs that value for Meta.
        if (!DB::table('whatsapp_settings')->where('vendor_id', 1)->exists()) {
            DB::table('whatsapp_settings')->insert([
                'vendor_id'    => 1,
                'verify_token' => 'oc_' . Str::random(32),
                'api_version'  => 'v21.0',
                'is_active'    => 2,
                'ai_enabled'   => 1,
                'created_at'   => now(),
                'updated_at'   => now(),
            ]);
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('whatsapp_chat_messages');
        Schema::dropIfExists('whatsapp_conversations');
        Schema::dropIfExists('whatsapp_settings');
        Schema::table('question_answer', function (Blueprint $t) {
            foreach (['is_available', 'reorder_id', 'source'] as $c) {
                if (Schema::hasColumn('question_answer', $c)) $t->dropColumn($c);
            }
        });
    }
};
